---
- name: Update and upgrade system packages
  hosts: all  # Replace with your target group or 'all' for all hosts
  become: yes  # Privilege escalation required for package management
  gather_facts: yes  # Required to determine OS distribution

  tasks:
    - name: Update apt package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Upgrade all apt packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Clean up apt packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Update dnf packages (Fedora/CentOS/RHEL)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Clean up dnf packages (Fedora/CentOS/RHEL)
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    # Optional: Reboot system if required (uncomment to enable)
    # - name: Check if reboot is required
    #   ansible.builtin.stat:
    #     path: /var/run/reboot-required
    #   register: reboot_required
    #   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    # - name: Reboot system
    #   ansible.builtin.reboot:
    #     msg: "System reboot after updates"
    #     reboot_timeout: 300
    #   when: reboot_required.stat.exists
