---
- name: Update and upgrade system packages
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    # Debian/Ubuntu systems
    - name: Update apt package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Upgrade all apt packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    # RHEL family (CentOS, RHEL) and Amazon Linux 2
    - name: Update all yum packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_pkg_mgr == "yum" or ansible_os_family == "RedHat"

    - name: Clean up yum packages
      ansible.builtin.yum:
        clean_requirements_on_remove: yes
      when: ansible_pkg_mgr == "yum" or ansible_os_family == "RedHat"

    # Check for reboot requirement
    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_debian
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (RedHat family and Amazon Linux)
      ansible.builtin.command: needs-restarting -r
      register: reboot_required_rhel
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    # Reboot if required
    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Rebooting after system updates"
        reboot_timeout: 300
        post_reboot_delay: 60
      when: >
        (ansible_os_family == "Debian" and reboot_required_debian.stat.exists) or
        (ansible_os_family == "RedHat" and reboot_required_rhel.rc == 1)