---
- name: Update and upgrade all systems
  hosts: all
  become: yes  # Privilege escalation required
  gather_facts: yes  # Needed to detect OS distribution and version

  tasks:
    # Debug to confirm detection
    - name: Debug system facts
      ansible.builtin.debug:
        msg:
          - "Distribution: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "OS Family: {{ ansible_os_family }}"
          - "Package Manager: {{ ansible_pkg_mgr }}"

    # Debian/Ubuntu: Update and upgrade with apt
    - name: Update apt package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache valid for 1 hour
      when: ansible_os_family == "Debian"

    - name: Upgrade all apt packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"

    - name: Clean up apt packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_os_family == "Debian"

    # Fedora/RHEL/CentOS with dnf: Update with dnf
    - name: Update dnf packages (Fedora/RHEL/CentOS with dnf)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
        use_backend: dnf4  # Explicitly use dnf4 to avoid backend detection issues
      when: >
        ansible_distribution in ["Fedora", "RedHat", "CentOS"] and
        "dnf" in ansible_facts.packages  # Only run if dnf is installed

    - name: Clean up dnf packages (Fedora/RHEL/CentOS with dnf)
      ansible.builtin.dnf:
        autoremove: yes
        use_backend: dnf4
      when: >
        ansible_distribution in ["Fedora", "RedHat", "CentOS"] and
        "dnf" in ansible_facts.packages

    # Amazon Linux 2 / Older RHEL: Update with yum
    - name: Update yum packages (Amazon Linux 2, older RHEL)
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      when: >
        ansible_distribution == "Amazon" or
        (ansible_distribution in ["CentOS", "RedHat"] and ansible_pkg_mgr == "yum")

    - name: Clean up yum packages (Amazon Linux 2, older RHEL)
      ansible.builtin.yum:
        clean_requirements_on_remove: yes
      when: >
        ansible_distribution == "Amazon" or
        (ansible_distribution in ["CentOS", "RedHat"] and ansible_pkg_mgr == "yum")

    # Check for reboot requirement (multi-distro)
    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_debian
      when: ansible_os_family == "Debian"
      ignore_errors: yes

    - name: Check if reboot is required (RedHat family, including Amazon Linux)
      ansible.builtin.command: needs-restarting -r
      register: reboot_required_rhel
      failed_when: false  # Exit code 1 means reboot needed, not a failure
      changed_when: false
      when: ansible_os_family == "RedHat"  # Covers Amazon Linux, CentOS, RHEL

    # Reboot if required
    - name: Reboot system if required
      ansible.builtin.reboot:
        msg: "Rebooting after system updates"
        reboot_timeout: 300  # 5 minutes
      when: >
        (ansible_os_family == "Debian" and reboot_required_debian.stat.exists) or
        (ansible_os_family == "RedHat" and reboot_required_rhel.rc == 1)