---
- name: Deploy Wazuh Agent on Debian-based systems
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    wazuh_agent_url: "https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.11.0-1_amd64.deb"
    wazuh_agent_package: "wazuh-agent_4.11.0-1_amd64.deb"
    wazuh_manager: "192.168.20.82"  # Use IP instead of hostname

  tasks:
    # Debug to confirm OS detection
    - name: Debug OS facts
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "Distribution: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "OS Family: {{ ansible_os_family }}"

    # Ensure the system is Debian-based
    - name: Fail if not Debian-based
      ansible.builtin.fail:
        msg: "This playbook is designed for Debian-based systems only."
      when: ansible_os_family != "Debian"

    # Update apt cache and install basic dependencies
    - name: Update apt cache and install basic dependencies
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ item }}"
        state: present
      loop:
        - lsb-release
        - libc6

    # Add Ubuntu Focal repo for libssl1.1 on newer systems (e.g., Ubuntu 22.04)
    - name: Add Ubuntu Focal repository for libssl1.1 (if needed)
      ansible.builtin.apt_repository:
        repo: "deb http://security.ubuntu.com/ubuntu focal-security main"
        state: present
        update_cache: yes
      when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_version is version('22.04', '>=')

    # Install libssl1.1 on newer Ubuntu versions
    - name: Install libssl1.1 on newer Ubuntu versions
      ansible.builtin.apt:
        name: libssl1.1
        state: present
      when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_version is version('22.04', '>=')
      ignore_errors: yes

    # Download the Wazuh agent package
    - name: Download Wazuh agent .deb package
      ansible.builtin.get_url:
        url: "{{ wazuh_agent_url }}"
        dest: "/tmp/{{ wazuh_agent_package }}"
        mode: "0644"
      register: download_result
      retries: 3
      delay: 5
      until: download_result is success

    # Install the Wazuh agent using apt
    - name: Install Wazuh agent package with apt
      ansible.builtin.apt:
        deb: "/tmp/{{ wazuh_agent_package }}"
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      register: install_result
      changed_when: install_result is changed

    # Ensure ossec.conf has the correct manager IP
    - name: Configure Wazuh agent to use manager IP
      ansible.builtin.lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: '^(\s*)<address>.*</address>'
        line: "      <address>{{ wazuh_manager }}</address>"
        insertafter: '<server>'
        backrefs: yes
      notify: Restart Wazuh agent

    # Clean up downloaded package
    - name: Remove downloaded .deb file
      ansible.builtin.file:
        path: "/tmp/{{ wazuh_agent_package }}"
        state: absent
      when: install_result is changed

    # Reload systemd daemon
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    # Enable Wazuh agent service
    - name: Enable Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: yes

    # Start Wazuh agent service (initial start)
    - name: Start Wazuh agent service
      ansible.builtin.systemd:
        name: wazuh-agent
        state: started

    # Verify Wazuh agent status
    - name: Check Wazuh agent status
      ansible.builtin.command: systemctl status wazuh-agent
      register: agent_status
      changed_when: false
      failed_when: agent_status.rc != 0

    - name: Debug Wazuh agent status
      ansible.builtin.debug:
        msg: "{{ agent_status.stdout_lines }}"

  handlers:
    # Restart Wazuh agent if config changes
    - name: Restart Wazuh agent
      ansible.builtin.systemd:
        name: wazuh-agent
        state: restarted